# permissions for end users to view memcachedexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedext-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memcachedexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcachedexts/status
  verbs:
  - get
