# permissions for end users to edit memcachedexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedext-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memcachedexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcachedexts/status
  verbs:
  - get
